name: Deploy to Hosting

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Update next.config.js for static export
        run: |
          echo "/** @type {import('next').NextConfig} */
          module.exports = {
            output: 'export',
            images: {
              unoptimized: true,
            },
            trailingSlash: true,
          }" > next.config.js
          
      - name: Build static site
        run: npm run build -- --no-lint
        
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: /public_html/
